version: "3"
services:
  plagiaat_rabbitmq:
    image: rabbitmq:management
    container_name: plagiaat_rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
  plagiaat_postgres:
    image: postgres:14
    container_name: plagiaat_postgres
    volumes:
      - plagiaat_postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  traefik:
    image: traefik
    container_name: plagiaat_traefik
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - plagiaatnet
    volumes:
      - ./docker_dev/traefik.yml:/etc/traefik/traefik.yml
      - ./docker_dev/traefik:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - ./azurite_data:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
networks:
  plagiaatnet:
    driver: bridge
volumes:
  plagiaat_postgres_volume: