name: Compile and create Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  buildjava:
    env:
      REGISTRY: ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_SUBMODULE_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Log in to the Container registry for docker images
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: github.ref_name == 'main' || github.ref_name == 'develop'

      - name: Cache gradle deps and builds
        uses: burrunan/gradle-cache-action@v1
        with:
            gradle-version: wrapper
            arguments: --no-daemon shadowJar

      - name: Build and push Docker images (Stable)
        uses: docker/build-push-action@v3.1.1
        if: github.ref_name == 'main'
        with:
          context: .
          file: ./Dockerfile.plagiaat
          push: true
          tags: ghcr.io/hugo-helder/plagiaatcontrole-service:stable

      - name: Build and push Docker images (Develop)
        uses: docker/build-push-action@v3.1.1
        if: github.ref_name == 'develop'
        with:
          context: .
          file: ./Dockerfile.plagiaat
          push: true
          tags: ghcr.io/hugo-helder/plagiaatcontrole-service:latest
