name: reviewdog
on: pull_request

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hu-dvandenham/action-checkstyle-newer-java@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          checkstyle_config: checkstyle.xml
          checkstyle_version: 10.4
          workdir: ./src

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          level: warning
